linter:
  rules:
    - unnecessary_statements
    - unnecessary_lambdas
    - avoid_renaming_method_parameters
    - camel_case_types
    - constant_identifier_names
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables

include: package:pedantic/analysis_options.yaml