linter:
  rules:
    - unnecessary_statements
    - unnecessary_lambdas
    - avoid_renaming_method_parameters
    - camel_case_types
    - constant_identifier_names
    - avoid_bool_literals_in_conditional_expressions
    - avoid_positional_boolean_parameters
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables