name: sudoku_game
description: A simple Sudoku game.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  provider: ^4.3.2+2

  pedantic: ^1.9.2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test:

  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.8.1

flutter:
  uses-material-design: true
  fonts:
    - family: Coolvetica
      fonts:
        - asset: assets/fonts/Coolvetica-Regular.ttf

# Splash Screen
flutter_native_splash:
  image: assets/images/splash_screen_small.png
  color: "D6E4EE"

# Launcher Icon
flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/images/splash_screen_small.png